name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Update"]
    types:
      - completed

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby-version: [2.6, 2.7, '3.0', 3.1, 3.2, head]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: ruby -v
        run: ruby -v
      - name: ls -lash
        run: ls -lash
      - name: pwd
        run: pwd
      - name: env
        run: env
      - name: Run tests for Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
        run: bundle config unset deployment && bundle exec m test/standard/runners/rubocop_test.rb:105
